name: Get version bump
description: Determine which version (major.minor.patch) to bump based on the PR body or provided input

inputs:
  docker-image:
    description: Image with build ros workspace
    required: true
  workspace-path:
    description: Path to ros workspace (inside docker)
    required: true
  outputs_path:
    description: JUnit xml results will be placed in this folder  
    required: true

runs:
  using: composite
  steps:
    -
      id: run_tests
      run: |
          export id=$(docker create ${{ inputs.docker-image }} );
          docker cp ${{ github.action_path }}/run_tests.sh $id:/;
          docker commit $id tmp;
          docker run -v ${{ inputs.outputs_path }}:/home/mul/outputs_path -e WS_PATH=${{ inputs.workspace-path }} --entrypoint=/run_tests.sh tmp;
      shell: bash
